### ISSUE TITLE
bug: Videos not loading

### ISSUE THREAD

**Issue by MrMikeJJ** [ReVanced/revanced-patches-template#981]
### Type

Error at runtime

### Bug description

The same as #838 but i cannot reopen that one.
The fix put in for #838 seems to have helped a lot, but the issue still happens just less frequently.

After watching a few videos, it then gets stuck loading the video indefinitely.
You can work around this buy skipping to the end of the video then using replay to restart playback.

### Steps to reproduce

1. Live in the UK / connect to UK VPN server
2. Try playing multiple videos
3. Video will get stuck loading

### Relevant log output

```shell
n/a
```

### Solution

You can work around this buy skipping to the end of the video then using replay to restart playback.

### Additional context

Not sure if it is related, but occasionally after using the skip to the end work around, the video will display the loading circle all the way through the video (while still playing).

This happening with the setting in "ReVanced -> Miscellaneous -> Fix video playback issues" enabled.

I tried updating to YouTube 17.43.36 but the issue persists.

Versions:
Android 8
Patched YouTube 17.43.36
Revanced Manager 0.0.39
Revanced Patches 2.102.1
Vanced microG 0.2.24.220220

Patches installed:
Custom Branding
General Ads
MicroG Support
Minimized Playback
Theme
Video Ads

This issue is assumed to be caused by MicroG: https://github.com/microg/GmsCore/issues/1870.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Please attach a recording.

**Comment by MrMikeJJ** [comment]
Attached video. 

https://user-images.githubusercontent.com/5191401/200125647-ad6cd7a7-3f51-45da-8e0e-7e3f9a6aa684.mp4

**Comment by oSumAtrIX** [comment]
Can you record if this happens on multiple videos?

**Comment by MrMikeJJ** [comment]
Happens 4 times on the attached clip.

Also on the 3rd one it happens on, you can see something strange (around 1m53s). It looks like it rewinds, even though i wasn't touching the screen at the time. (never seen it do that before, hence why i am mentioning it).


https://user-images.githubusercontent.com/5191401/200126787-220d37b4-dd73-4cb0-9243-6bc1ccbce109.mp4

**Comment by oSumAtrIX** [comment]
I can not reproduce this on my end on an account where this issue is present without applying the fix. To reproduce I would need access to the account to test the issue on.

**Comment by oSumAtrIX** [comment]
Seems like commit e756face362e4abf2c7b17afa536feed9b0cd631 failed. After a fix and a release for it, the issue should be solved

**Comment by MrMikeJJ** [comment]
With patches v2.104.0 it has massively improved, thank you.

But not totally fixed. It still happens occasionally, but only on the first video played after Revanced is opened.

**Comment by edegaudenzi** [comment]
Problem persists in exactly same modalities here, with the only exception that in my case it happens in all the videos: played and previewed.

My workaround is being connected to a VPN (nordvpn) pointing outside the UK, for example Paris or Milan.

LineageOS 18.1 (Android 11)
YouTube ReVanced non rooted - MicroG support

**Comment by bosbode** [comment]
I'm experiencing this problem as well in the Netherlands. As of today.

**Comment by oSumAtrIX** [comment]
Changes are rolled out to multiple countries.

**Comment by LisoUseInAIKyrios** [comment]
Try going into ReVanced settings and turning off all switches (including hide advertising).  Then ReVanced should behave exactly the same as stock YouTube (including showing ads).

After doing this, is the issue still present?

**Comment by oSumAtrIX** [comment]
This is not a ReVanced specific issue. Any client mod will cause this issue. This does not happen on mounted variant. Signature or package name is checked and server returns 403 on /videoplayback. The check can be outside of the app itself in GMS for example (or in non root variant in MicroG) or inside the app. I already spoofed every getPackageInfo call in YouTube but that did not help either, it is known that there is other ways to get the signature or package name (for example via context.getPackageName which i havent tried spoofing yet), or it was done in GMS/MicroG (which I havent looked into much either). In any case, this issue can be fixed by spoofing the signature and package name at some place properly.

**Comment by oSumAtrIX** [comment]
@LisoUseInAIKyrios I am able to reproduce in my dev env and can confirm that the root variant does not have this issue, hence why my conclusions on signature and package name.

**Comment by Besix2** [comment]
Same here in Germany non root version is not usable

**Comment by RaphiMC** [comment]
Same for me in Austria. Non root version not working on Android 9 (Videos load for me indefinitely and never start playing)

**Comment by immertroll** [comment]
I can confirm the issue with a non-root version from Germany.
The issue exists only, when I'm signed in with a Google account. No issues in incognito mode.

**Comment by Besix2** [comment]
It works on root variant without account signed in

**Comment by ILoveOpenSourceApplications** [comment]
This issue is related to microg and not related to ReVanced YouTube. So closing this as of now.

**Comment by senposage** [comment]
as a work around try disabling Push nofications and cloud messaging 
it looks like this is how google is detecting the vanced/microgms. 

it seems like there is some kind of timeout on whatever restiction they are using when vanced is detected as well switching accounts and using the other account for awhile seems to unrestrict the other account allowing video to play

**Comment by oSumAtrIX** [comment]
An exception is thrown at a certain place, so yeah, it's feasible
